### ISSUE TITLE
希望支持 Visual Studio Code

### ISSUE THREAD

**Issue by 834772509** [tuchg/ChinesePinyin-CodeCompletionHelper#1]

**Comment by tuchg** [comment]
隔壁已有支持哦，vscode 直接搜索中文补全就 ok

**Comment by nobodxbodon** [comment]
@834772509 欢迎试用 VS Code [中文代码快速补全](https://marketplace.visualstudio.com/items?itemName=CodeInChinese.ChineseInputAssistant)插件。

@tuchg 刚在知乎有幸听闻，前来问好！因为有用户之前建议[移植到 intelliJ](https://gitee.com/Program-in-Chinese/vscode_Chinese_Input_Assistant/issues/I1NZSP#note_2898324)，不知可否在我们的首页加上贵项目的链接？

**Comment by tuchg** [comment]
> @834772509 欢迎试用 VS Code [中文代码快速补全](https://marketplace.visualstudio.com/items?itemName=CodeInChinese.ChineseInputAssistant)插件。
> 
> @tuchg 刚在知乎有幸听闻，前来问好！因为有用户之前建议[移植到 intelliJ](https://gitee.com/Program-in-Chinese/vscode_Chinese_Input_Assistant/issues/I1NZSP#note_2898324)，不知可否在我们的首页加上贵项目的链接？

非常荣幸,我也可以在本项目加上您的链接

**Comment by nobodxbodon** [comment]
@tuchg 好啊！要不我们互相提个 pr？我们在[码云](https://gitee.com/Program-in-Chinese/vscode_Chinese_Input_Assistant)，不知您方便提 pr 不？

**Comment by tuchg** [comment]
> @tuchg 好啊！要不我们互相提个 pr？我们在[码云](https://gitee.com/Program-in-Chinese/vscode_Chinese_Input_Assistant)，不知您方便提 pr 不？

可以，这个项目在码云我也同步了

**Comment by nobodxbodon** [comment]
刚 [从这里](https://gitee.com/Program-in-Chinese/vscode_Chinese_Input_Assistant/pulls/21#note_14037341_conversation_67070496) 得知了 [新的 VS 类似功能插件](https://github.com/stratosblue/ChinesePinyinIntelliSenseExtender)，@stratosblue 你好。

**Comment by stratosblue** [comment]
@nobodxbodon 你好。。。
我是谁，我在哪儿，发生了啥

**Comment by nobodxbodon** [comment]
@stratosblue 很高兴认识。
之前在此项目和VSC插件都打过下手，一路来看到不少正面反馈，年初还亲见了Jetbrains官方 [添加拼音补全功能](https://youtrack.jetbrains.com/issue/IDEA-251113)，因此发现其他IDE的类似插件时颇为振奋。
个人感觉几个项目目标相似而各种发挥空间还很大。希望多多交流、互通有无、相辅相成，像 [这个新开issue](https://gitee.com/Program-in-Chinese/vscode_Chinese_Input_Assistant/issues/I5YGO3) 就受了自定义字典的启发。

**Comment by stratosblue** [comment]
@nobodxbodon 哈哈哈，好的，了解了，请大佬多多指教

**Comment by tuchg** [comment]
@nobodxbodon  @stratosblue  你好，大家可以提个pr在项目readme中相互推荐，目前jetbrains和vscode相互推荐，不知道你是否有兴趣加入？

**Comment by stratosblue** [comment]
@tuchg 可以可以，感谢大佬

**Comment by tuchg** [comment]
> @tuchg 可以可以，感谢大佬

欢迎 pr
