### ISSUE TITLE
kotlin语言无法使用

### ISSUE THREAD

**Issue by liuyike233** [tuchg/ChinesePinyin-CodeCompletionHelper#10]
最近学习了kotlin，在Android studio上没有提示，语法提示框后面没有追加拼音
https://i.loli.net/2020/11/18/3J86se5ZxHzL4nB.png

**Comment by tuchg** [comment]
插件是这样的，输入拼音才会触发提示，如sz，she等应该就会正确触发，对直接输入中文不会做解析

**Comment by tuchg** [comment]
> 插件是这样的，输入拼音才会触发提示，如sz，she等应该就会正确触发，对直接输入中文不会做解析

测试了下，的确存在问题

**Comment by liuyike233** [comment]
> > 插件是这样的，输入拼音才会触发提示，如sz，she等应该就会正确触发，对直接输入中文不会做解析
> 
> 测试了下，的确存在问题，目前仅发现kotlin存在该问题

对我也只是发现kotlin不行，觉得这个插件很好用，装了之后效率贼高，反正proground混淆了中文和英文没什么区别，写代码反而是更快更易读了，写了一些中文库之后那些中文编程软件可以退出市场了哈哈

**Comment by DXueShengKa** [comment]
我也是kotlin用不了

**Comment by nobodxbodon** [comment]
@tuchg 不知有何头绪吗？感觉这个问题影响还挺大，毕竟 kotlin 是它们家主打语言。不知有没有用得上帮忙的地方。

**Comment by tuchg** [comment]
> @tuchg 不知有何头绪吗？感觉这个问题影响还挺大，毕竟 kotlin 是它们家主打语言。不知有没有用得上帮忙的地方。

无头绪，询问过官方，暂时没有建设性建议

**Comment by nobodxbodon** [comment]
@tuchg 请问相关issue是哪个？想学习一下细节。

**Comment by tuchg** [comment]
> @tuchg 请问相关issue是哪个？想学习一下细节。

[.](https://intellij-support.jetbrains.com/hc/en-us/community/posts/360009917119-Why-PrefixMatcher-cannot-be-triggered-only-by-kotlin-completions-)

**Comment by nobodxbodon** [comment]
@tuchg 刚看了这个[补全插件的官方文档](https://www.plugin-dev.com/intellij/custom-language/code-completion/)，不知有没有试过添加个测试用例来复现这个问题？

**Comment by nobodxbodon** [comment]
不知是否相关，我的 pycharm 下，python 补全有效
![Screen Shot 2020-12-19 at 2 45 25 PM](https://user-images.githubusercontent.com/392497/102701153-e7240080-4208-11eb-87e7-b5ed882dc61e.png)


但 java/kotlin 都无效（[java 例程链接](https://github.com/program-in-chinese/java_in_hours_chn/blob/master/%E8%81%8A%E5%A4%A9%E6%9C%BA%E5%99%A8%E4%BA%BA/%E8%81%8A%E5%A4%A9%E6%9C%BA%E5%99%A8%E4%BA%BA%E7%B1%BB.java)）：
![Screen Shot 2020-12-19 at 2 38 43 PM](https://user-images.githubusercontent.com/392497/102701080-24d45980-4208-11eb-93f1-d39e34d4cbcc.png)

pycharm 版本信息：
PyCharm 2020.3 (Community Edition)
Build #PC-203.5981.165, built on December 1, 2020
Runtime version: 11.0.9+11-b1145.21 x86_64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o.

**Comment by tuchg** [comment]
> 不知是否相关，我的 pycharm 下，python 补全有效
> ![Screen Shot 2020-12-19 at 2 45 25 PM](https://user-images.githubusercontent.com/392497/102701153-e7240080-4208-11eb-87e7-b5ed882dc61e.png)
> 
> 但 java/kotlin 都无效（[java 例程链接](https://github.com/program-in-chinese/java_in_hours_chn/blob/master/%E8%81%8A%E5%A4%A9%E6%9C%BA%E5%99%A8%E4%BA%BA/%E8%81%8A%E5%A4%A9%E6%9C%BA%E5%99%A8%E4%BA%BA%E7%B1%BB.java)）：
> ![Screen Shot 2020-12-19 at 2 38 43 PM](https://user-images.githubusercontent.com/392497/102701080-24d45980-4208-11eb-93f1-d39e34d4cbcc.png)
> 
> pycharm 版本信息：
> PyCharm 2020.3 (Community Edition)
> Build #PC-203.5981.165, built on December 1, 2020
> Runtime version: 11.0.9+11-b1145.21 x86_64
> VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o.

pycharm是针对python的，没装插件自然无效

**Comment by nobodxbodon** [comment]
刚测的结果仍然和 [功能文档](https://github.com/tuchg/ChinesePinyin-CodeCompletionHelper/blob/master/doc/%E5%8A%9F%E8%83%BD%E6%B5%8B%E8%AF%95.md#kotlin) 一样。标识符如果有字母前缀则有补全项：
<img width="295" alt="Screen Shot 2021-12-30 at 1 38 14 PM" src="https://user-images.githubusercontent.com/392497/147789759-c1080fc1-9f7c-49a9-88e2-ca8eca6da64f.png">

如果无字母前缀则无法补全：
<img width="295" alt="Screen Shot 2021-12-30 at 1 38 31 PM" src="https://user-images.githubusercontent.com/392497/147789744-3c335955-3e73-4917-80dd-b911afa74a80.png">

是否要再开此issue？
