### ISSUE TITLE
【建议】新版本 IDE 无法安装和使用

### ISSUE THREAD

**Issue by CharlieJ0hn** [tuchg/ChinesePinyin-CodeCompletionHelper#16]
**Is your feature request related to a problem? Please describe.**
idea 和 webstorm 更新到了 2020.3，插件无法正常安装、开启、使用

**Describe the solution you'd like**
希望大佬修复一下

**Describe alternatives you've considered**
没有

**Additional context**
![image](https://user-images.githubusercontent.com/9925064/100827095-e2382080-3496-11eb-91f1-3fe2bc67c6da.png)

**Comment by tuchg** [comment]
已修复
