### ISSUE TITLE
请教搭建环境问题

### ISSUE THREAD

**Issue by nobodxbodon** [tuchg/ChinesePinyin-CodeCompletionHelper#18]
正在尝试搭建开发环境，在 IDEA 社区版下打开项目，运行 gradle 任务 verifyPlugin 或者 runIde 时，都报错：
```
Execution failed for task ':patchPluginXml'.
> org.jetbrains.changelog.exceptions.HeaderParseException: Header '[unspecified]' does not contain version number. 

```
看了 settings.gradle.kts 里有 `version(pluginVersion)`，不知是何问题？

**Comment by nobodxbodon** [comment]
不知与版本有关否？

IntelliJ IDEA 2020.3 (Community Edition)
Build #IC-203.5981.155, built on November 30, 2020
Runtime version: 11.0.9+11-b1145.21 x86_64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o.
Non-Bundled Plugins: com.thoughtworks.gauge, org.intellij.scala

**Comment by nobodxbodon** [comment]
发现如果删除[最近 commit](https://github.com/tuchg/ChinesePinyin-CodeCompletionHelper/commit/29e0d5abd20f9331529066a3e8544bde717e3f38) 自动添加的 [unspecified] 一行，此问题就消失了。

不知这个添加 changelog 的自动任务是由什么触发的？为何会出现 [unspecified] 而不是具体版本号呢？

**Comment by nobodxbodon** [comment]
将 build.gradle.kts 中此部分去掉也可避免问题，但不知有何副效应否：
```
        changeNotes(closure {
            changelog.getLatest().toHTML()
        })
```
在提 pr 之前，商量一下如何处理最合适？

**Comment by tuchg** [comment]
> 在提 pr 之前，商量一下如何处理最合适？

去掉不可
