### ISSUE TITLE
好像在 pycharm 的 marketplace 搜不到？

### ISSUE THREAD

**Issue by nobodxbodon** [tuchg/ChinesePinyin-CodeCompletionHelper#2]
![Screen Shot 2020-08-10 at 2 13 11 PM](https://user-images.githubusercontent.com/392497/89832052-ba9e0080-db13-11ea-9938-373f0dc0f682.png)

不知是因为还在审核吗？版本信息：

PyCharm 2020.2 (Community Edition)
Build #PC-202.6397.98, built on July 27, 2020

**Comment by tuchg** [comment]
是的,还在审核,这两天应该会审核完
