### ISSUE TITLE
【Bug】输入法默认显示在左下角，无法看到汉字部分

### ISSUE THREAD

**Issue by czs-zzu** [tuchg/ChinesePinyin-CodeCompletionHelper#26]
## 请事先检查下列事项

- [ √] 已了解或使用过本项目
- [ √]  issue/feature 尚未有前人提出

## 编程语言
Python

## 当前表现
打字框默认出现在屏幕的左下方，只露出拼音部分，汉字部分没有露出。输入框可以拖出来，但是一打字就会回到左下角

> 提供代码片段或截图
![2021-01-06 21-38-35屏幕截图](https://user-images.githubusercontent.com/33375652/103774745-05db2180-5068-11eb-932b-2279564a78f1.png)

## 使用环境

* 插件版本:0.1.4
* IDE版本:Pycharm2020.3.2(Community Edition)
* 操作系统版本:Ubuntu 20.04.1 LTS

**Comment by nobodxbodon** [comment]
mac 下 pycharm 2020.3 搜狗拼音输入法正常：
![Screen Shot 2021-01-06 at 9 51 14 AM](https://user-images.githubusercontent.com/392497/103803056-e52db000-5004-11eb-8875-207b3ad1feec.png)

可以确认一下这个问题是否是由插件引起的吗？比如其他 IDE 下有无此问题、删除插件后问题是否消失等等。

**Comment by tuchg** [comment]
Linux发行版普遍存在该问题，与插件无关

我也曾经折腾过很久，有说JDK问题，有说输入法组件问题，建议在相关内容查找
