### ISSUE TITLE
【Bug】idea pro, 在编辑js时候不能拼音语法提示,java文件可以

### ISSUE THREAD

**Issue by liuyike233** [tuchg/ChinesePinyin-CodeCompletionHelper#32]
## 请事先检查下列事项

- [x] 已了解或使用过本项目
- [x]  issue/feature 尚未有前人提出

## 编程语言
javascript
## 预期表现
想要正常使用
## 当前表现
不能提示
## 重现错误场景
idea pro, 在编辑js时候不能拼音语法提示,java文件可以
> 提供代码片段或截图
https://sm.ms/image/4myNXAwMB5D2vKV
## 使用环境

* 插件版本:0.1.5
* IDE版本（如 IDEA 2020.2）: 最新版
* 操作系统版本（如 Mac OS 10.15.6）: bigsur11.2

**Comment by tuchg** [comment]
已初步修复，但不能达到如 Java一样完美的效果

如要达到该效果，可安装 2020.2 及以下版本及插件 0.0.5 （理论本版本也可，且更佳）版本
