### ISSUE TITLE
【Bug】goland IDEA 不能使用

### ISSUE THREAD

**Issue by BelieveQvQ** [tuchg/ChinesePinyin-CodeCompletionHelper#34]
## 请事先检查下列事项

- 

- [x] 已了解或使用过本项目

- [x]  issue/feature 尚未有前人提出

## 编程语言
Go
## 重现错误场景
![image](https://user-images.githubusercontent.com/24773068/108576381-698b8680-7358-11eb-959a-0802ae0025b7.png)

## 使用环境

* 插件版本 :  0.1.6
* IDE版本 : 2020.3
* 操作系统版本如  :  Windows 10 19042.804

**Comment by tuchg** [comment]
暂时没时间彻底解决这个问题，可以在标识符前加合法ascii 字符解决如 m数据库等
