### ISSUE TITLE
【建议】请求支持五笔

### ISSUE THREAD

**Issue by HaujetZhao** [tuchg/ChinesePinyin-CodeCompletionHelper#35]
**Is your feature request related to a problem? Please describe.**

才在 vscode 上使用了中文补全插件，设为五笔后，太好用了。只是有许多项目不适合 vscode，得用 pycharm，目前 pycharm 上的补全还不支持五笔。

**Describe the solution you'd like**

希望可以支持五笔变量补全

**Comment by tuchg** [comment]
会出的，但近半年是不可能了，下半年会试着迭代下

**Comment by nobodxbodon** [comment]
有幸遇到一位例程使用中文标识符的热门python教程作者（[孙兴华《中文讲Python从入门到办公自动化》](https://www.bilibili.com/video/BV1gt4y1D7W8?p=1&share_medium=android&share_plat=android&share_source=COPY&share_tag=s_i&timestamp=1623799509&unique_k=eMxjUR)），交流时也有此需求：
![Screen Shot 2021-06-15 at 8 08 29 PM](https://user-images.githubusercontent.com/392497/122152230-d221d600-ce15-11eb-814b-0b21849d1552.png)

**Comment by tuchg** [comment]
> 有幸遇到一位例程使用中文标识符的热门python教程作者（[孙兴华《中文讲Python从入门到办公自动化》](https://www.bilibili.com/video/BV1gt4y1D7W8?p=1&share_medium=android&share_plat=android&share_source=COPY&share_tag=s_i&timestamp=1623799509&unique_k=eMxjUR)），交流时也有此需求：
> ![Screen Shot 2021-06-15 at 8 08 29 PM](https://user-images.githubusercontent.com/392497/122152230-d221d600-ce15-11eb-814b-0b21849d1552.png)

可以,会优先安排这个需求,近期忙着实习

**Comment by nobodxbodon** [comment]
用几个五笔 98 数据作了个简陋演示，实现很粗糙（没咋用过 kotlin）希望有一点点帮助，[见此commit](https://github.com/nobodxbodon/ChinesePinyin-CodeCompletionHelper/commit/285132082fc34f2ac231fd0b145cb7e00aa9c0b6)：
![Screen Shot 2021-06-17 at 12 59 36 AM](https://user-images.githubusercontent.com/392497/122357581-bba87700-cf08-11eb-8e68-f8bd1338ee21.png)

**Comment by tuchg** [comment]
> 用几个五笔 98 数据作了个简陋演示，实现很粗糙（没咋用过 kotlin）希望有一点点帮助，[见此commit](https://github.com/nobodxbodon/ChinesePinyin-CodeCompletionHelper/commit/285132082fc34f2ac231fd0b145cb7e00aa9c0b6)： ![Screen Shot 2021-06-17 at 12 59 36 AM](https://user-images.githubusercontent.com/392497/122357581-bba87700-cf08-11eb-8e68-f8bd1338ee21.png)

近期考虑以rime自定义字典的方式一劳永逸地支持各类码，你觉得如何
* 是否需要内置部分码表？（繁杂，个人不了解哪些为高频，应该被内置）
* 除全拼外，引导用户去自行下载/导入码表 （个人倾向于此）

**Comment by nobodxbodon** [comment]
> 除全拼外，引导用户去自行下载/导入码表 （个人倾向于此）

确认一下，内置码表（用户无需自行下载导入）的优势是开发工作量更小、用户使用更简便；劣势是安装时间更长？

**Comment by tuchg** [comment]
> > 除全拼外，引导用户去自行下载/导入码表 （个人倾向于此）
> 
> 确认一下，内置码表（用户无需自行下载导入）的优势是开发工作量更小、用户使用更简便；劣势是安装时间更长？

优势是用户使用简便

劣势是开发工作量大，打包体积更大，且内置的码表不一定能满足用户需求

**Comment by nobodxbodon** [comment]
> 劣势是开发工作量大

为何呢？解析码表和搜索是都需开发的吧。支持用户导入的话还要加界面提示、校验内容和格式等等功能？

> 且内置的码表不一定能满足用户需求

vsc之前内置的码表好像没看到反馈说不够用。

@lsby 感觉这和你 [现在做的](https://gitee.com/Program-in-Chinese/vscode_Chinese_Input_Assistant/issues/I5YGO3) 颇有关联。一道探讨？

**Comment by tuchg** [comment]
> > 劣势是开发工作量大
> 
> 为何呢？解析码表和搜索是都需开发的吧。支持用户导入的话还要加界面提示、校验内容和格式等等功能？
> 
> > 且内置的码表不一定能满足用户需求
> 
> vsc之前内置的码表好像没看到反馈说不够用。
> 
> @lsby 感觉这和你 [现在做的](https://gitee.com/Program-in-Chinese/vscode_Chinese_Input_Assistant/issues/I5YGO3) 颇有关联。一道探讨？

码表直接引导用户使用 rime 输入法的，给个地址让用户去下载，导入校验暂时没有去考虑，可以支持点击文件在 ide 中直接跳转修改
