### ISSUE TITLE
【Bug】安卓xml文件重复提示

### ISSUE THREAD

**Issue by liuyike233** [tuchg/ChinesePinyin-CodeCompletionHelper#37]
## 请事先检查下列事项

- [ x ] 已了解或使用过本项目
- [ ]  issue/feature 尚未有前人提出

## 编程语言
xml

## 当前表现
会出现两个一样的提示
## 重现错误场景
安卓xml文件
> 提供代码片段或截图
![image](https://user-images.githubusercontent.com/3820712/110661946-03c84700-8200-11eb-992b-4451196475bd.png)

## 使用环境

* 插件版本:1.7
* IDE版本（如 IDEA 2020.2）:EAP最新
* 操作系统版本（如 Mac OS 10.15.6）:bigsur 11.2.3

**Comment by tuchg** [comment]
java 或 kotlin里有出现这种情况吗

**Comment by liuyike233** [comment]
> java 或 kotlin里有出现这种情况吗

没有,目前发现只有xml里出现

**Comment by liuyike233** [comment]
> java 或 kotlin里有出现这种情况吗

还有个问题,明明完全匹配的项,还是会排在最后一个,这个可以优化一下我觉的基本就很好用了

**Comment by tuchg** [comment]
> > java 或 kotlin里有出现这种情况吗
> 
> 还有个问题,明明完全匹配的项,还是会排在最后一个,这个可以优化一下我觉的基本就很好用了

java 应该不会出现该问题吧，是kotlin 吗

**Comment by liuyike233** [comment]
> > > java 或 kotlin里有出现这种情况吗
> > 
> > 
> > 还有个问题,明明完全匹配的项,还是会排在最后一个,这个可以优化一下我觉的基本就很好用了
> 
> java 应该不会出现该问题吧，是kotlin 吗

![image](https://user-images.githubusercontent.com/3820712/111017189-d12f7180-83ec-11eb-8b1c-f60fe5c7eee7.png)
是java

**Comment by liuyike233** [comment]
> > > java 或 kotlin里有出现这种情况吗
> > 
> > 
> > 还有个问题,明明完全匹配的项,还是会排在最后一个,这个可以优化一下我觉的基本就很好用了
> 
> java 应该不会出现该问题吧，是kotlin 吗

用的是idea eap,插件是最新版1.7

**Comment by tuchg** [comment]
> > > > java 或 kotlin里有出现这种情况吗
> > > 
> > > 
> > > 还有个问题,明明完全匹配的项,还是会排在最后一个,这个可以优化一下我觉的基本就很好用了
> > 
> > 
> > java 应该不会出现该问题吧，是kotlin 吗
> 
> 用的是idea eap,插件是最新版1.7

嗯，有时间看下，先将就着用吧，最近没啥时间

**Comment by tuchg** [comment]
> > > > > java 或 kotlin里有出现这种情况吗
> > > > 
> > > > 
> > > > 还有个问题,明明完全匹配的项,还是会排在最后一个,这个可以优化一下我觉的基本就很好用了
> > > 
> > > 
> > > java 应该不会出现该问题吧，是kotlin 吗
> > 
> > 
> > 用的是idea eap,插件是最新版1.7
> 
> 嗯，有时间看下，先将就着用吧，最近没啥时间

也可以试试回退版本到 0.1.5看看

**Comment by nobodxbodon** [comment]
@liuyike233 关于排序，在 1.6 下测，似乎与命名有关，”按钮“有同样问题：

![Screen Shot 2021-03-13 at 7 19 26 PM](https://user-images.githubusercontent.com/392497/111056929-32c8fd80-8438-11eb-9e65-d792d68483b8.png)
但改为”按键“就好了：
![Screen Shot 2021-03-13 at 8 08 30 PM](https://user-images.githubusercontent.com/392497/111056931-378db180-8438-11eb-8974-e85ec553479c.png)

**Comment by tuchg** [comment]
还能看到吗？今天试了下 没能复现该场景
