### ISSUE TITLE
下载安装插件并且重启之后，依旧无法显示中文界面

### ISSUE THREAD

**Issue by wyw0416** [tuchg/ChinesePinyin-CodeCompletionHelper#38]
![QQ截图20210321151916](https://user-images.githubusercontent.com/65116329/111897140-315f8c80-8a59-11eb-8177-8611ef0f8f3a.png)
如图所示，求大神帮忙解决，谢谢各位了

**Comment by liuyike233** [comment]
> ![QQ截图20210321151916](https://user-images.githubusercontent.com/65116329/111897140-315f8c80-8a59-11eb-8177-8611ef0f8f3a.png)
> 如图所示，求大神帮忙解决，谢谢各位了

这个插件并不是汉化界面用的

**Comment by nobodxbodon** [comment]
pycharm 下刚试了 0.1.7 有效：
![Screen Shot 2021-03-21 at 12 54 30 AM](https://user-images.githubusercontent.com/392497/111897952-1ac91f00-89e0-11eb-9d15-caa926da0fac.png)

**Comment by liuyike233** [comment]
> pycharm 下刚试了 0.1.7 有效：
> ![Screen Shot 2021-03-21 at 12 54 30 AM](https://user-images.githubusercontent.com/392497/111897952-1ac91f00-89e0-11eb-9d15-caa926da0fac.png)

你说的是中文界面,这个插件是中文补全,不是汉化界面.你可以试试

> pycharm 下刚试了 0.1.7 有效：
> ![Screen Shot 2021-03-21 at 12 54 30 AM](https://user-images.githubusercontent.com/392497/111897952-1ac91f00-89e0-11eb-9d15-caa926da0fac.png)

他说的是中文界面,这个插件不是汉化界面用的,是补全用的.汉化界面是另外一个插件Chinese simplify

**Comment by wyw0416** [comment]
哦哦，实在是抱歉，小白没用弄清楚其中具体功能，我也在plugins上搜索了Chinese simplify，但是没有相应插件，是需要更新pycharm才能搜到嘛？
![捕获](https://user-images.githubusercontent.com/65116329/111899208-06c80080-8a66-11eb-8482-32f4b62f0c70.PNG)
![屏幕截图 2021-03-21 165341](https://user-images.githubusercontent.com/65116329/111899209-0891c400-8a66-11eb-8eda-a50370509024.png)

**Comment by liuyike233** [comment]
> 哦哦，实在是抱歉，小白没用弄清楚其中具体功能，我也在plugins上搜索了Chinese simplify，但是没有相应插件，是需要更新pycharm才能搜到嘛？
> ![捕获](https://user-images.githubusercontent.com/65116329/111899208-06c80080-8a66-11eb-8482-32f4b62f0c70.PNG)
> ![屏幕截图 2021-03-21 165341](https://user-images.githubusercontent.com/65116329/111899209-0891c400-8a66-11eb-8eda-a50370509024.png)

![image](https://user-images.githubusercontent.com/3820712/111901183-5b24ad80-8a71-11eb-9fcc-82575f869b98.png)
你应该需要的是这个

**Comment by wyw0416** [comment]
对，但是我输入进去没有找到相应的插件
