### ISSUE TITLE
clion 2020.3.3 无法使用补全功能

### ISSUE THREAD

**Issue by xunanmu** [tuchg/ChinesePinyin-CodeCompletionHelper#39]
![GIF 2021-3-21 22-29-27](https://user-images.githubusercontent.com/34336047/111908785-891be900-8a95-11eb-8044-e58249d0096e.gif)

**Comment by tuchg** [comment]
需要在中文前添加ascill 码范围的合法字符
以后会试着修复

**Comment by nobodxbodon** [comment]
@xunanmu 已知 Go 和 Kotlin 有类似情况（见首页"已知问题")

**Comment by tuchg** [comment]
[官方 IDEA-251113 已提供支持](https://github.com/JetBrains/intellij-community/commit/71a587c4b23667bb09d1f1dc830647b133953a9e)
可静候此项更新
