### ISSUE TITLE
在Rider 2020.2 C#项目中无汉语补全

### ISSUE THREAD

**Issue by zxgamekingdom** [tuchg/ChinesePinyin-CodeCompletionHelper#4]
您好大佬：
       我安装了Rider 2020.2后，建立C#的控制台与WPF项目都无法进行汉语补全。PyCharm 2020.2是可以使用的。在同一个虚拟机中。
       我尝试过重置我的Rider 2020.2 的设置，创建新的纯净的虚拟机安装Rider 2020.2 也无法使用。 
       顺便提一下，您有没有兴趣让您的这个插件支持Resharper。

**Comment by tuchg** [comment]
Rider 的体系与一般的IntelliJ不太一样，好像是有独立的体系，可以考虑支持

**Comment by zxgamekingdom** [comment]
谢谢大佬

**Comment by tspersonal** [comment]
2021.1.5版本中貌似也不能使用
