### ISSUE TITLE
【Bug】golang没中文提示 可以优化一下吗

### ISSUE THREAD

**Issue by duolabmeng6** [tuchg/ChinesePinyin-CodeCompletionHelper#40]
https://github.com/duolabmeng6/goefun

你好 golang 没提示 

![image](https://user-images.githubusercontent.com/59047063/112784900-579eb100-9085-11eb-90db-c367d7aa1487.png)

**Comment by duolabmeng6** [comment]
![image](https://user-images.githubusercontent.com/59047063/112785239-21156600-9086-11eb-8dcf-e8c47a0427fd.png)
不开启插件的情况下是正常提示的

**Comment by nobodxbodon** [comment]
刚试了用 w 做前缀可以：
![Screen Shot 2021-03-29 at 2 07 59 AM](https://user-images.githubusercontent.com/392497/112813992-ade30400-9033-11eb-9c62-d041a1cb44a3.png)

**Comment by tuchg** [comment]
理论上可以的，确定插件安装成功了没？

**Comment by nobodxbodon** [comment]
针对“_写到文件”标识符测了全部 26 个字母前缀，输入“_xd”看有无补全项，发现这六个字母作前缀时没有：d e i r s t ，其他二十个字母都有。

**Comment by tuchg** [comment]
> 针对“_写到文件”标识符测了全部 26 个字母前缀，输入“_xd”看有无补全项，发现这六个字母作前缀时没有：d e i r s t ，其他二十个字母都有。

我去这是啥毛病

**Comment by duolabmeng6** [comment]
> 针对“ _写到文件”标识符测算的全部26个字母前缀，输入“ _xd”看有无补全项，发现这六个字母作前缀时没有：dirst，其他二十个字母都有。

这么尴尬的吗 哈哈哈 我正好用的是 E 所以...就没了?...

**Comment by duolabmeng6** [comment]
> > 针对“_写到文件”标识符测了全部 26 个字母前缀，输入“_xd”看有无补全项，发现这六个字母作前缀时没有：d e i r s t ，其他二十个字母都有。
> 
> 我去这是啥毛病，核查了 clion 没这问题

https://github.com/duolabmeng6/goefun

大佬你把代码拉下来可空呗...真不行

![image](https://user-images.githubusercontent.com/59047063/113243712-178a3900-92e6-11eb-8b12-34b061f81334.png)

要输入 _x 才出的来...

**Comment by tuchg** [comment]
> > > 针对“_写到文件”标识符测了全部 26 个字母前缀，输入“_xd”看有无补全项，发现这六个字母作前缀时没有：d e i r s t ，其他二十个字母都有。
> > 
> > 
> > 我去这是啥毛病，核查了 clion 没这问题
> 
> https://github.com/duolabmeng6/goefun
> 
> 大佬你把代码拉下来可空呗...真不行
> 
> ![image](https://user-images.githubusercontent.com/59047063/113243712-178a3900-92e6-11eb-8b12-34b061f81334.png)
> 
> 要输入 _x 才出的来...

简直匪夷所思，暂时没时间修复，5~6 月才有时间

**Comment by duolabmeng6** [comment]
不知道大佬解决了吗

**Comment by duolabmeng6** [comment]
定时来打卡 看看大佬解决了没~

**Comment by tuchg** [comment]
> 定时来打卡 看看大佬解决了没~

最近忙着考试没时间维护，5月下旬到6月中旬可能会试着重构下

**Comment by duolabmeng6** [comment]
> > 定时来打卡 看看大佬解决了没~
> 
> 最近忙着考试没时间维护，5月下旬到6月中旬可能会试着重构下

祝你考试顺顺利利~~你是最棒的~~

**Comment by duolabmeng6** [comment]
大佬 可以在你的项目推荐一下我的中文函数库吗 

python 易函数 (完美支持你的插件)
https://github.com/duolabmeng6/pyefun


golang 易函数(等你bug修复好就很到位)
https://github.com/duolabmeng6/goefun

**Comment by tuchg** [comment]
> 大佬 可以在你的项目推荐一下我的中文函数库吗
> 
> python 易函数 (完美支持你的插件)
> https://github.com/duolabmeng6/pyefun
> ![image](https://user-images.githubusercontent.com/59047063/118903052-73b62480-b949-11eb-92f3-26bc0a73ebde.png)
> 
> golang 易函数(等你bug修复好就很到位)
> https://github.com/duolabmeng6/goefun

ok 可以在README推荐下 你可以提交下PR

**Comment by duolabmeng6** [comment]
大佬大佬 求修复这个bug..
pycharm的输入体验极好.. pyefun输入体验极好
goland输入goefun输入的命令体验太糟糕拉~好拉胯啊~

**Comment by tuchg** [comment]
> 大佬大佬 求修复这个bug..
> pycharm的输入体验极好.. pyefun输入体验极好
> goland输入goefun输入的命令体验太糟糕拉~好拉胯啊~

..... 争取吧，这个bug挺棘手的

**Comment by duolabmeng6** [comment]
> > 大佬大佬 求修复这个bug..
> > pycharm的输入体验极好.. pyefun输入体验极好
> > goland输入goefun输入的命令体验太糟糕拉~好拉胯啊~
> 
> ..... 争取吧，这个bug挺棘手的

我测试了一下 如果不用 . 语法导包的话 还是能用的..
但是就会出现画风迥异的代码 例如  E.E调试输出() 看着也太别扭了...

**Comment by tuchg** [comment]
[官方 IDEA-251113 已提供支持](https://github.com/JetBrains/intellij-community/commit/71a587c4b23667bb09d1f1dc830647b133953a9e)

经此底层支持，插件已可运行完整
