### ISSUE TITLE
常用命令 图片  系统 等等

### ISSUE THREAD

**Issue by nuo010** [tuchg/ChinesePinyin-CodeCompletionHelper#43]
def 图片_修改_尺寸(path,保存地址,横=100,竖=100):
    im=Image.open(path)
    w,h=im.size
    print(w,h)
    dImg = im.resize((横, 竖), Image.ANTIALIAS)#横竖长度
    dImg.save(保存地址)
    print("修改完成",保存地址)
def 图片_压缩_大小(infile, outfile='', mb=150, step=10, quality=80):
    """不改变图片尺寸压缩到指定大小
    :param infile: 压缩源文件
    :param outfile: 压缩文件保存地址
    :param mb: 压缩目标，KB
    :param step: 每次调整的压缩比率
    :param quality: 初始压缩比率
    :return: 压缩文件地址，压缩文件大小
    """
    o_size = os.path.getsize(infile)/ 1024
    if o_size <= mb:
        return infile

    while o_size > mb:
        im = Image.open(infile)
        im.save(outfile, quality=quality)
        if quality - step < 0:
            break
        quality -= step
        o_size = os.path.getsize(outfile)/ 1024
    return outfile, os.path.getsize(outfile)/ 1024
def 拼接路径(*args):
    "例 参数 '111','222','333'   111\222\333   参数开头和结尾不要有\ 参数中间可以添加反斜杠"
    return os.path.join(*args)

**Comment by nobodxbodon** [comment]
是给  [pyefun 项目](https://github.com/duolabmeng6/pyefun) 的吧？
