### ISSUE TITLE
希望优化一下中途输入智能提示问题

### ISSUE THREAD

**Issue by duolabmeng6** [tuchg/ChinesePinyin-CodeCompletionHelper#44]
![image](https://user-images.githubusercontent.com/59047063/119443312-00068400-bd5c-11eb-96d4-12c714265a0b.png)

**Comment by duolabmeng6** [comment]
![image](https://user-images.githubusercontent.com/59047063/119443886-e6b20780-bd5c-11eb-8e53-c4785f222a70.png)

ide本身是支持这种功能的..但是需要英文

**Comment by tuchg** [comment]
最近在试着从根源解决补全问题，会留意的

**Comment by duolabmeng6** [comment]
大佬可以给一个联系方式吗 我也在开发ide插件 请向您请教一下

**Comment by liuyike233** [comment]
> 最近在试着从根源解决补全问题，会留意的

这个提议很好啊,我也想说这个中断之后接着补全,现在每次要删完才可以哈哈

**Comment by tuchg** [comment]
> 大佬可以给一个联系方式吗 我也在开发ide插件 请向您请教一下

可能也提供不了什么帮助，你有问题的话可以在这里发下，尽力回答

**Comment by duolabmeng6** [comment]
> > 大佬可以给一个联系方式吗 我也在开发ide插件 请向您请教一下
> 
> 可能也提供不了什么帮助，你有问题的话可以在这里发下，尽力回答

感谢大佬~~

**Comment by stfenjobs** [comment]
+1 
我也遇到这个问题了，希望大佬可以抽空，解决下

谢谢大佬

**Comment by tuchg** [comment]
v0.1.8 已修复

**Comment by duolabmeng6** [comment]
> v0.1.8 已修复

大佬牛逼~~~
