### ISSUE TITLE
【Bug】开启后模糊只能提示失效

### ISSUE THREAD

**Issue by geekscloud** [tuchg/ChinesePinyin-CodeCompletionHelper#45]
## 请事先检查下列事项

- [x] 已了解或使用过本项目
- [x]  issue/feature 尚未有前人提出

## 编程语言
JAVA
## 预期表现
原智能提示无需按序输入完整单词提示,只需首字母或者片段, 即可筛选
## 当前表现
现 智能提示只能按顺序连续输入单词才可筛选结果,首字母或者跳序, 会导致结果丢失
## 可能的解决方案
排除了一圈设置, 卸载插件可解决

## 重现错误场景

> 提供代码片段或截图
正常情况下
<img width="416" alt="截屏2021-06-05 20 03 51" src="https://user-images.githubusercontent.com/24413839/120891075-291af480-c639-11eb-827a-37b598e81bb0.png">

安装插件后: 输入cc会无结果

## 使用环境
mac 和 win 一致

* 插件版本: 0.1.7
* IDE版本: IDEA 2021.1.2
* 操作系统版本: Mac OS 11.4 / win10 21H1

**Comment by nobodxbodon** [comment]
Gitee 之前有相同报告：https://gitee.com/tuchg/ChinesePinyin-CodeCompletionHelper/issues/I3PJ0Y

**Comment by tuchg** [comment]
v0.1.8 已修复
