### ISSUE TITLE
【测试】本地运行 test 或 runide 报错

### ISSUE THREAD

**Issue by nobodxbodon** [tuchg/ChinesePinyin-CodeCompletionHelper#46]
![Screen Shot 2021-06-16 at 8 47 34 AM](https://user-images.githubusercontent.com/392497/122312495-2d60d080-cec9-11eb-8c7c-d199367a05a8.png)

运行 test：
```
FAILURE: Build failed with an exception.
* What went wrong:
Could not determine the dependencies of task ':test'.
> Could not resolve all dependencies for configuration ':testRuntimeClasspath'.
   > Cannot find builtin plugin JavaScript for IDE: .../.gradle/caches/modules-2/files-2.1/com.jetbrains.intellij.idea/ideaIU/LATEST-EAP-SNAPSHOT/9edff542761a100e86bf07ace3136a120f405e5b/ideaIU-LATEST-EAP-SNAPSHOT
```

运行 runide：
```
Could not determine the dependencies of task ':prepareSandbox'.
> Cannot find builtin plugin JavaScript for IDE ...
```

根据 [intellij 官网此贴](https://intellij-support.jetbrains.com/hc/en-us/community/posts/360010812280-Cannot-find-builtin-plugin-JavaScriptLanguage)提到：
> People in the JB dev slack channel seem to suggest to just not build with EAP for now:

将 gradle.properties 中 `platformVersion=LATEST-EAP-SNAPSHOT`改回：

```
platformVersion=2020.3.2
```

test 和 runide 都可以正常运行。

不确定如何处理，也许还是用一个特定版本（隔段时间更新）省得最新 snapshot 里有这那的问题？

**Comment by tuchg** [comment]
可以，但是目前的测试模块感觉作用不大，看看能否让它更具实用性

**Comment by nobodxbodon** [comment]
主要是 runide 也会报同样错误不能运行，比较影响开发。不大确定上个CI怎么没报错，也许那时的LATEST-EAP-SNAPSHOT还没这个问题。。

**Comment by tuchg** [comment]
> 主要是 runide 也会报同样错误不能运行，比较影响开发。不大确定上个CI怎么没报错，也许那时的LATEST-EAP-SNAPSHOT还没这个问题。。

是 EAP 普遍存在好像
