### ISSUE TITLE
【建议】去除 README.md 里的英文翻译

### ISSUE THREAD

**Issue by abersheeran** [tuchg/ChinesePinyin-CodeCompletionHelper#5]
我不觉得这个项目会有看不懂中文的人使用，加上英文只会让整体排版变得很别扭。如果非要加英文说明，应当再开一个 README-en.md 比较合理。

**Comment by liuxilu** [comment]
写上JB要求吧，不然还要点进此页

**Comment by hcen1997** [comment]
只有想要知道原因的人才会点进这个页面, 
没有必要非写在readme里面让所有人知道

**Comment by liuxilu** [comment]
谁不对此疑惑呢？几个字而已。

**Comment by tuchg** [comment]
> 只有想要知道原因的人才会点进这个页面,
> 没有必要非写在readme里面让所有人知道

目前应该是被我去除了吧

**Comment by xianyu21** [comment]
打卡

**Comment by sheldon-cooper0** [comment]
打卡😘

**Comment by tuchg** [comment]
这是来自QQ邮箱的假期自动回复邮件。
 
您好，我最近正在休假中，无法亲自回复您的邮件。我将在假期结束后，尽快给您回复。

**Comment by abc6239657639** [comment]
> 写上JB要求吧，不然还要点进此页

说的真好！

**Comment by DongyunLee** [comment]
打卡~

**Comment by yangyang233333** [comment]
是的

**Comment by KSroido** [comment]
围观

**Comment by liujiaqi7998** [comment]
围观
