### ISSUE TITLE
拼错了？

### ISSUE THREAD

**Issue by GenTort666** [tuchg/ChinesePinyin-CodeCompletionHelper#50]
## 请事先检查下列事项

- [x] 已了解或使用过本项目
- [X]  issue/feature 尚未有前人提出

## 编程语言
HTML
## 预期表现
长度叫做ChangDu
## 当前表现
它成ZhangDu了
## 可能的解决方案
把Z改成C

## 重现错误场景
![截屏2021-08-15 下午12 22 27](https://user-images.githubusercontent.com/86411424/129467061-6a420f04-97c4-42f6-bd30-0557ece8b8b0.png)

## 使用环境

* 插件版本:0.1.8
* IDE版本:WebStorm 2021.2
* 操作系统版本:macOS Monterey Beta(12.0,21A5294g)

**Comment by nobodxbodon** [comment]
pycharm里，输入 chd有补全：
<img width="241" alt="Screen Shot 2021-08-15 at 12 18 48 AM" src="https://user-images.githubusercontent.com/392497/129470416-b220a87f-1d62-4b1a-b684-bb6873182c6a.png">

**Comment by tuchg** [comment]
只是显示问题，后续会添加一个选项对这个功能进行补偿

**Comment by tuchg** [comment]
目前输入预期多音拼音即可显示预期效果，暂无法实现该功能
