### ISSUE TITLE
大佬  什么时间支持 Rider 中文提示啊? 

### ISSUE THREAD

**Issue by AnyAnq** [tuchg/ChinesePinyin-CodeCompletionHelper#51]
我试了旧版2018.3.2 rider 最新版2021.1.3rider 都不能用

**Comment by tuchg** [comment]
在排了在排了

**Comment by AnyAnq** [comment]
辛苦辛苦! 先star了

**Comment by tuchg** [comment]
可以试试2022版本

**Comment by nobodxbodon** [comment]
在rider 2022.1.1 试用版测试，未装插件的补全效果：
<img width="754" alt="Screen Shot 2022-05-21 at 10 23 07 PM" src="https://user-images.githubusercontent.com/392497/169680195-fded7f00-1ee3-40e0-9aff-4469472a0428.png">

安装后的效果
<img width="476" alt="Screen Shot 2022-05-21 at 10 24 12 PM" src="https://user-images.githubusercontent.com/392497/169680196-0d41e1f7-7bae-44aa-90f5-cfe3c755f965.png">
：
