### ISSUE TITLE
请教如何想all autocomplete那样指定一个word list files？

### ISSUE THREAD

**Issue by ocde** [tuchg/ChinesePinyin-CodeCompletionHelper#52]
测试了下发现目前需要将我维护的wordlist 打开才能调用，如何可以在设置里指定一个文件来自动调用？
感谢！

**Comment by tuchg** [comment]
all autocomplete 是？

**Comment by ocde** [comment]
你可以搜下这个插件的关键词，

后来我试了貌似即便不打开也可以调用，但设置中没有明确的指定文件的选项。
