### ISSUE TITLE
在Datagrip中无法进行补全 可以显示但是输入拼音后提示框消失

### ISSUE THREAD

**Issue by AiSY-Yang** [tuchg/ChinesePinyin-CodeCompletionHelper#53]
## 编程语言
SQL

## 预期表现
可以中文补全

## 当前表现
提示框中可以显示中文拼音 但是输入拼音后不能补全

## 重现错误场景

> 提供代码片段或截图
![image](https://user-images.githubusercontent.com/20870087/134866277-7ad247df-6853-42ca-9abf-a9e6f51e620e.png)
![image](https://user-images.githubusercontent.com/20870087/134866315-6118fee6-9190-49dd-a460-3d8f2110239a.png)
当输入拼音的时候补全框消失

## 使用环境

* 插件版本:0.1.8
* IDE版本（Datagrip 2021.2.2）:
* 操作系统版本（如 Win10）:
DBMS: MySQL (版本 8.0.25) 
区分大小写: 普通形式=lower, 分隔形式=lower 
驱动程序: MySQL Connector/J (版本 mysql-connector-java-8.0.25 (Revision: 08be9e9b4cba6aa115f9b27b215887af40b159e0)，JDBC4.2)

**Comment by nobodxbodon** [comment]
2021.3.3 下测试 0.1.8，数据源 sqlite，问题可重现。
```sql
CREATE TABLE 学生(
   ID INT PRIMARY KEY      NOT NULL,
   姓名           CHAR(50) NOT NULL
);
```
表名无补全：`delete from xue`
列名也无补全：`delete from 学生 where xm`，如果xm改为 i 则有“ID”补全项。

**Comment by tuchg** [comment]
安装2022.2+的版本即可
