### ISSUE TITLE
【Bug】2021.2.2 Java补全异常

### ISSUE THREAD

**Issue by tuchg** [tuchg/ChinesePinyin-CodeCompletionHelper#54]
## 请事先检查下列事项

- [x] 已了解或使用过本项目
- [x]  issue/feature 尚未有前人提出

## 编程语言
Java
## 预期表现
正常输入补全
## 当前表现
输入后无补全提示
## 重现错误场景

> 提供代码片段或截图

## 使用环境

* 插件版本:
* IDE版本（如 IDEA 2020.2）: 
* 操作系统版本（如 Mac OS 10.15.6）:

**Comment by nobodxbodon** [comment]
请问这个问题还在吗？

**Comment by tuchg** [comment]
这是来自QQ邮箱的假期自动回复邮件。
 
您好，我最近正在休假中，无法亲自回复您的邮件。我将在假期结束后，尽快给您回复。
