### ISSUE TITLE
【Bug】怎么关掉你那个愚蠢的通知，你知道给撒谎都不会的萌新多大困扰吗？

### ISSUE THREAD

**Issue by vihenry** [tuchg/ChinesePinyin-CodeCompletionHelper#55]
## 请事先检查下列事项

- [ ] 已了解或使用过本项目
- [ ]  issue/feature 尚未有前人提出

## 重现错误场景

> 提供代码片段或截图

## 使用环境

* 插件版本:
* IDE版本（如 IDEA 2020.2）:
* 操作系统版本（如 Mac OS 10.15.6）:

**Comment by nobodxbodon** [comment]
？是指在插件安装完毕后的弹窗吗？印象里只出现一次，关闭之后不再出现了。
不知为何困扰呢？

**Comment by tuchg** [comment]
？撒谎？
