### ISSUE TITLE
【Bug】求修复kotlin无法使用的问题

### ISSUE THREAD

**Issue by liuyike98** [tuchg/ChinesePinyin-CodeCompletionHelper#56]
有无修复kotlin的计划呢？现在写安卓我不怎么用java，kotlin基本没法用，即便在变量前面加个字母也不行

**Comment by nobodxbodon** [comment]
2022.1 EAP 测试效果如下：
<img width="367" alt="Screen Shot 2022-03-07 at 7 31 23 PM" src="https://user-images.githubusercontent.com/392497/157161141-65203b2f-ac22-4cf1-83a0-79f724ea0d98.png">

Build #IU-221.4906.8, built on March 3, 2022

**Comment by tuchg** [comment]
> 有无修复kotlin的计划呢？现在写安卓我不怎么用java，kotlin基本没法用，即便在变量前面加个字母也不行

经测试AndroidStudio 2021.1.1 支持前缀字母中文补全，但是可能不太灵光，可以多尝试尝试
等到AS同步到2022后，就可以完美支持了

**Comment by liuyike98** [comment]
https://user-images.githubusercontent.com/87092276/157998703-ef00c12b-63f7-49f7-b9d4-ff04f21fdede.mp4
![image](https://user-images.githubusercontent.com/87092276/157998749-857ffa5f-fad7-418b-bb0d-6ff93931e4fd.png)

不行，IDEA 2021.3 最新版测试，kotlin无法使用
@nobodxbodon @tuchg

**Comment by nobodxbodon** [comment]
@liuyike98 请待 2022.1 再试试吧。楼上已经测过 EAP 版本可用。

**Comment by tuchg** [comment]
这是来自QQ邮箱的假期自动回复邮件。
 
您好，我最近正在休假中，无法亲自回复您的邮件。我将在假期结束后，尽快给您回复。

**Comment by tuchg** [comment]
![image](https://user-images.githubusercontent.com/24775733/158001431-0c697d75-9332-4375-b03a-6f7a812bc419.png)
![image](https://user-images.githubusercontent.com/24775733/158001461-1a25bf02-7a55-4b59-b953-2f7c27c50c51.png)



> https://user-images.githubusercontent.com/87092276/157998703-ef00c12b-63f7-49f7-b9d4-ff04f21fdede.mp4 ![image](https://user-images.githubusercontent.com/87092276/157998749-857ffa5f-fad7-418b-bb0d-6ff93931e4fd.png)
> 
> 不行，IDEA 2021.3 最新版测试，kotlin无法使用 @nobodxbodon @tuchg

经过测试是可行的

**Comment by tuchg** [comment]
这是来自QQ邮箱的假期自动回复邮件。
 
您好，我最近正在休假中，无法亲自回复您的邮件。我将在假期结束后，尽快给您回复。
