### ISSUE TITLE
安装好后，并没哟展示中文

### ISSUE THREAD

**Issue by wuqiang-001** [tuchg/ChinesePinyin-CodeCompletionHelper#59]
![image](https://user-images.githubusercontent.com/85499933/164909804-10df1c4e-3f65-4044-94f1-b3fad3356181.png)

IED 已经正常从新启动，依旧是英文

**Comment by tuchg** [comment]
这个插件并不是翻译插件

**Comment by wuqiang-001** [comment]
你在描述什么？

**Comment by tuchg** [comment]
> 你在描述什么？

插件是代码补全插件，并不是你想要的把界面翻译成中文的插件
