### ISSUE TITLE
goland下面自动补全有问题,

### ISSUE THREAD

**Issue by xushushun** [tuchg/ChinesePinyin-CodeCompletionHelper#6]
中文函数名图标消失,由于go外部调用首字母必须大写,所以加入W+中文函数名,输入w也没有提示了

**Comment by tuchg** [comment]
v0.0.5已修复

**Comment by nobodxbodon** [comment]
@tuchg  从码云的 [此 issue](https://gitee.com/tuchg/ChinesePinyin-CodeCompletionHelper/issues/I2BMSN) 继续，在 build.gradle.kts 中添加下面后，就能运行goland 目标平台了（这是mac下的路径）：
```
     runIde {
        ideDirectory("/Applications/GoLand.app/Contents/")
    }
```
现在尝试加点日志，[在这](https://intellij-support.jetbrains.com/hc/en-us/community/posts/206779715/comments/206163615) 看到用 com.intellij.openapi.diagnostic.Logger , 但不知如何用。有何建议吗？

**Comment by nobodxbodon** [comment]
@tuchg 你先忙，这里记录一下调试进展。[这个 commit](https://github.com/program-in-chinese/ChinesePinyin-CodeCompletionHelper/commit/871d3450ee7f7a4cf99f719b2252e2f13787054d) 添加了日志和运行平台设置，下面是日志输出：
```
2021-01-08 22:49:32,991 [ 258122]   WARN -                           前缀匹配 - 匹配中——前缀：wm 全名：W名字 
2021-01-08 22:49:32,991 [ 258122]   WARN -                           前缀匹配 - 匹配个数：2 前缀长度：2 
2021-01-08 22:49:33,034 [ 258165]   WARN -                           中文补全 - 补全中 
2021-01-08 22:49:33,035 [ 258166]   WARN -                           中文补全 - 前缀匹配之后！ 
2021-01-08 22:49:33,049 [ 258180]   WARN -                           前缀匹配 - 匹配中——前缀：wm 全名：struct 
2021-01-08 22:49:33,050 [ 258181]   WARN -                           前缀匹配 - 匹配中——前缀：wm 全名：map 
2021-01-08 22:49:33,050 [ 258181]   WARN -                           前缀匹配 - 匹配中——前缀：wm 全名：slice 
2021-01-08 22:49:33,051 [ 258182]   WARN -                           前缀匹配 - 匹配中——前缀：wm 全名：array 
2021-01-08 22:49:33,052 [ 258183]   WARN -                           前缀匹配 - 匹配中——前缀：wm 全名：func 
```

初步看来，输入 wm 之后，ChinesePrefixMatcher 是匹配了 "W名字"，但不知为何没有传入 `resultSet.runRemainingContributors` 内。

**Comment by nobodxbodon** [comment]
刚发现，注释掉这行：
```java
resultSet.restartCompletionOnAnyPrefixChange()
```
就有补全项了，虽然还是没有图标：

![Screen Shot 2021-01-08 at 11 22 26 PM](https://user-images.githubusercontent.com/392497/104086439-f9dc9480-520c-11eb-8aa2-2a36d67b9664.png)

不知这句有何功能呢？

**Comment by tuchg** [comment]
> 刚发现，注释掉这行：
> 
> ```java
> resultSet.restartCompletionOnAnyPrefixChange()
> ```
> 
> 就有补全项了，虽然还是没有图标：
> 
> ![Screen Shot 2021-01-08 at 11 22 26 PM](https://user-images.githubusercontent.com/392497/104086439-f9dc9480-520c-11eb-8aa2-2a36d67b9664.png)
> 
> 不知这句有何功能呢？

若无这句补全触发会出问题，图标相关看lookupelement

**Comment by zhongguo168a** [comment]
在最新版的goland中还是无法正常使用

输入s显示
![image](https://user-images.githubusercontent.com/2868766/104285624-db1d1d00-54ee-11eb-9b44-901b2f94b367.png)


再次输入s
![image](https://user-images.githubusercontent.com/2868766/104285662-e8d2a280-54ee-11eb-8f44-d9782941efe7.png)

提示消失，正确的应该还有提示

**Comment by nobodxbodon** [comment]
@tuchg 
> 若无这句补全触发会出问题

不知有没有具体例子？去掉此句后在 Java 下测试似乎没看出不妥。

变量：
![Screen Shot 2021-01-13 at 6 40 22 PM](https://user-images.githubusercontent.com/392497/104537920-b64ca680-55cf-11eb-89df-2708f31d251d.png)

方法：
![Screen Shot 2021-01-13 at 6 40 43 PM](https://user-images.githubusercontent.com/392497/104537953-cbc1d080-55cf-11eb-98ab-d88a07107e56.png)


类：
![Screen Shot 2021-01-13 at 6 41 48 PM](https://user-images.githubusercontent.com/392497/104537968-d41a0b80-55cf-11eb-8de8-8853fa8f2204.png)

**Comment by nobodxbodon** [comment]
intellij 源码里，`restartCompletionOnAnyPrefixChange` [这段](https://github.com/JetBrains/intellij-community/blob/0b6ef9a85e41beafdf46d73b1c46bd301ec9fb89/platform/analysis-api/src/com/intellij/codeInsight/completion/CompletionResultSet.java#L187)：

```java
  /**
   * Request that the completion contributors be run again when the user changes the prefix in any way.
   */
  public void restartCompletionOnAnyPrefixChange() {
    restartCompletionOnPrefixChange(StandardPatterns.string());
  }
```
看起来像是指定在前缀修改后重新跑一遍 contributor。但即便删去了这句 `resultSet.restartCompletionOnAnyPrefixChange()`，刚测试了 Java 代码补全，根据日志， `fillCompletionVariants` 仍然在前缀修改（比如 l -> li）后重新运行了。

还是没看出这句用途。。😓

**Comment by tuchg** [comment]
> intellij 源码里，`restartCompletionOnAnyPrefixChange` [这段](https://github.com/JetBrains/intellij-community/blob/0b6ef9a85e41beafdf46d73b1c46bd301ec9fb89/platform/analysis-api/src/com/intellij/codeInsight/completion/CompletionResultSet.java#L187)：
> 
> ```java
>   /**
>    * Request that the completion contributors be run again when the user changes the prefix in any way.
>    */
>   public void restartCompletionOnAnyPrefixChange() {
>     restartCompletionOnPrefixChange(StandardPatterns.string());
>   }
> ```
> 
> 看起来像是指定在前缀修改后重新跑一遍 contributor。但即便删去了这句 `resultSet.restartCompletionOnAnyPrefixChange()`，刚测试了 Java 代码补全，根据日志， `fillCompletionVariants` 仍然在前缀修改（比如 l -> li）后重新运行了。
> 
> 还是没看出这句用途。。😓

你这里的测试并不是真实场景，自然看不出来，这里我记得是针对一个个输入的时候，比如`zhong`真实场景下你必然输入z、zh、zho...等，就和它的说明一样，每次输入都启动下我们这个贡献器，（一次输入到最终确认可能只会激活一次）不然激活不了，可能也可以从其他方面优化下

**Comment by nobodxbodon** [comment]
刚确认了一下 addElement 的调用情况，在拼音部分添加了个时间戳。每次键入时，可以看到同样文本的补全项的时间戳在更新。

输入 w：
![Screen Shot 2021-01-16 at 1 54 22 AM](https://user-images.githubusercontent.com/392497/104808880-e6e23b00-579d-11eb-8298-a0a3f3199902.png)

输入 ww:
![Screen Shot 2021-01-16 at 1 54 33 AM](https://user-images.githubusercontent.com/392497/104808892-f9f50b00-579d-11eb-8197-be206be86ad7.png)

如果删除 restartCompletionOnAnyPrefixChange， 那么每次键入时，补全项不会更新：

键入 w：
![Screen Shot 2021-01-16 at 1 50 48 AM](https://user-images.githubusercontent.com/392497/104808815-8bb04880-579d-11eb-9717-5800e4cdab51.png)

键入 ww：
![Screen Shot 2021-01-16 at 1 51 04 AM](https://user-images.githubusercontent.com/392497/104808820-8f43cf80-579d-11eb-963b-931722cf8429.png)

键入 wwz：
![Screen Shot 2021-01-16 at 1 51 21 AM](https://user-images.githubusercontent.com/392497/104808824-979c0a80-579d-11eb-96a7-4bb8572de18c.png)

这样看来，是不是所有匹配的补全项在输入第一个字符时就被添加了？那么之后键入更多字符时，就不会再有新的补全项需要添加，是否就不需要 restartCompletionOnAnyPrefixChange 了？

**Comment by tuchg** [comment]
这两天我看看，看来还是得写下单元测试

测试的情况有 大小写混搭中英文各种混搭还有位置首末，如果都正常那就按你的来吧

>看你的测试情况是都首位英文，换全中文看看呢

**Comment by nobodxbodon** [comment]
全中文的话 go 下，输入 ”z“ 补全不出，是否有 restart 都一样。不过如果没有 restart 时，输入”中“会有补全，不是本插件添加的补全项（没有拼音）：
![Screen Shot 2021-01-17 at 9 48 24 AM](https://user-images.githubusercontent.com/392497/104851357-61e44800-58a9-11eb-8db2-7f754da8ffea.png)


另外，在 java 下比较了有无 restart 时的补全项更新情况（时间戳变化），居然发现两种都更新了。看起来，是两种语言补全机制不大一样？

**Comment by tuchg** [comment]
每个语言都有自己的贡献器

**Comment by nobodxbodon** [comment]
@tuchg 关于单元测试，是添加类似下面这个的针对 countContainsSomeChar 的用例吗？如果忙的话我可以试着 pr。

https://github.com/tuchg/ChinesePinyin-CodeCompletionHelper/blob/caf09b39338b4b301806d7fe2561178deaf4e7d4/src/test/kotlin/CompletionTests.kt#L61

**Comment by tuchg** [comment]
> @tuchg 关于单元测试，是添加类似下面这个的针对 countContainsSomeChar 的用例吗？如果忙的话我可以试着 pr。
> 
> https://github.com/tuchg/ChinesePinyin-CodeCompletionHelper/blob/caf09b39338b4b301806d7fe2561178deaf4e7d4/src/test/kotlin/CompletionTests.kt#L61

我的不标准,按你的来吧

**Comment by nobodxbodon** [comment]
@tuchg 单元测试没发现什么问题，要不把 restartCompletionOnAnyPrefixChange 删去后做个比较全面的测试？除了 [楼上](https://github.com/tuchg/ChinesePinyin-CodeCompletionHelper/issues/6#issuecomment-759889595) 的这几个测试场景，还有哪些呢？需要测试 Java/IC 之外的组合吗？

另外，我的 goland 试用在 2 月 1 日到期，如果需要继续用的话估计要试着申请个 [开源项目许可证](https://www.jetbrains.com/community/opensource/#support)？

**Comment by tuchg** [comment]
> @tuchg 单元测试没发现什么问题，要不把 restartCompletionOnAnyPrefixChange 删去后做个比较全面的测试？除了 [楼上](https://github.com/tuchg/ChinesePinyin-CodeCompletionHelper/issues/6#issuecomment-759889595) 的这几个测试场景，还有哪些呢？需要测试 Java/IC 之外的组合吗？
> 
> 另外，我的 goland 试用在 2 月 1 日到期，如果需要继续用的话估计要试着申请个 [开源项目许可证](https://www.jetbrains.com/community/opensource/#support)？

如果可以的话,可以试着独立一个类去测试下各个语言的输入

开源许可证,我之前申请了,但就我这一份

**Comment by nobodxbodon** [comment]
@tuchg 请问插件商店有没有提供IDE 平台或者编程语言的使用统计数据？比如说在所有安装了本插件的 IDE 中，IntelliJ IDEA CE、Pycharm 等等各占比多少？或者有没有针对 Java、Python 等的统计？
这样可以从占比最高的 IDE 开始测试，如果有些 IDE 占比过小，可以暂时跳过测试？

**Comment by tuchg** [comment]
> @tuchg 请问插件商店有没有提供IDE 平台或者编程语言的使用统计数据？比如说在所有安装了本插件的 IDE 中，IntelliJ IDEA CE、Pycharm 等等各占比多少？或者有没有针对 Java、Python 等的统计？
> 这样可以从占比最高的 IDE 开始测试，如果有些 IDE 占比过小，可以暂时跳过测试？



Category | Downloads
-- | --
PyCharm Professional | 14159
PyCharm Community | 13153
IntelliJ IDEA Ultimate | 12624
PhpStorm | 3204
WebStorm | 2750
IntelliJ IDEA Community | 2650
Android Studio | 1324
CLion | 1311
GoLand | 1308
DataGrip | 964
Other | 605
Rider | 300
PyCharm Edu | 274
RubyMine | 46
AppCode | 34
MPS | 16
Site | 1
  |

**Comment by nobodxbodon** [comment]
@tuchg 好，我有 PyCharm Community、IntelliJ IDEA Community、GoLand，就先测试这三个了。

**Comment by tuchg** [comment]
> @tuchg 好，我有 PyCharm Community、IntelliJ IDEA Community、GoLand，就先测试这三个了。

ok。辛苦了，因为要备考,我最近半年可能都没时间维护了
