### ISSUE TITLE
【Bug】开启本插件后，先输入汉字后，无法补全了

### ISSUE THREAD

**Issue by zhouzpd** [tuchg/ChinesePinyin-CodeCompletionHelper#61]
## 请事先检查下列事项

- [ √] 已了解或使用过本项目
- [ √]  issue/feature 尚未有前人提出

## 编程语言
Pycharm

## 预期表现
输入汉字后不影响自带的中文变量补全功能
![image](https://user-images.githubusercontent.com/47655351/179525518-42f11c58-9114-491e-83c3-402dc9d6b3d2.png)

## 当前表现
开启插件后，输入拼音可提示补全，但如果先输入汉字，则无法提示补全

## 可能的解决方案
无

## 重现错误场景

> 提供代码片段或截图
![image](https://user-images.githubusercontent.com/47655351/179525760-72d5ae53-0629-4a11-82fa-c9e22fc50f4d.png)
## 使用环境

* 插件版本:
* IDE版本（如 IDEA 2020.2）:Pycharm 2021.3.3
* 操作系统版本（如 Mac OS 10.15.6）:Win10

**Comment by tuchg** [comment]
需求是否有些不太合理 插件本意就是更好的输入补全，何必还费劲打中文 @nobodxbodon

**Comment by zhouzpd** [comment]
是这样的，用中文变量后，输入法就不可避免的会用到中文，有时候输入法切换不对，由于手指记忆，会快速打出中文来（按空格上屏），这样想要补全就必须先删掉中文，再重新输入拼音（按enter上屏），这和平时打字的习惯不太一样。

这个输入中文补全的插件我觉得主要的场景是，在英文输入法下，**打字时直接上屏了拼音后，不需要删除也可补全**。但不应该再打出中文后反而不能补全了。

在用中文编程时，我一般是使用中文输入法（也方便写注释），然后通过AutoHotKey强行把标点符号替换为英文符号，这样便无需频繁切换输入法了。

**Comment by tuchg** [comment]
> 是这样的，用中文变量后，输入法就不可避免的会用到中文，有时候输入法切换不对，由于手指记忆，会快速打出中文来（按空格上屏），这样想要补全就必须先删掉中文，再重新输入拼音（按enter上屏），这和平时打字的习惯不太一样。
> 
> 这个输入中文补全的插件我觉得主要的场景是，在英文输入法下，**打字时直接上屏了拼音后，不需要删除也可补全**。但不应该再打出中文后反而不能补全了。
> 
> 在用中文编程时，我一般是使用中文输入法（也方便写注释），然后通过AutoHotKey强行把标点符号替换为英文符号，这样便无需频繁切换输入法了。

嗯嗯

**Comment by nobodxbodon** [comment]
@tuchg 是不是这句之前要加一个”如果可以直接匹配则返回true“的判断？

https://github.com/tuchg/ChinesePinyin-CodeCompletionHelper/blob/5cac289bfa781ab0363f1d5fc4b4dd31928ce378/src/main/kotlin/com/github/tuchg/nonasciicodecompletionhelper/completion/ChinesePrefixMatcher.kt#L20

**Comment by tuchg** [comment]
> @tuchg 是不是这句之前要加一个”如果可以直接匹配则返回true“的判断？
> 
> https://github.com/tuchg/ChinesePinyin-CodeCompletionHelper/blob/5cac289bfa781ab0363f1d5fc4b4dd31928ce378/src/main/kotlin/com/github/tuchg/nonasciicodecompletionhelper/completion/ChinesePrefixMatcher.kt#L20

嘿嘿 可以试着pr
