### ISSUE TITLE
【Bug】提示候选词重复

### ISSUE THREAD

**Issue by jiangshengxin** [tuchg/ChinesePinyin-CodeCompletionHelper#63]
## 编程语言
> PHP

## 预期表现
> 候选词不要重复

## 当前表现
> 候选词重复

## 重现错误场景

> 提供代码片段或截图
![image](https://user-images.githubusercontent.com/29392026/184115535-466af974-8e4a-410d-bdd1-e05f03ab8f9e.png)

## 使用环境
win11

* 插件版本:  `0.1.10`
* IDE版本（如 IDEA 2020.2）: `PHPStorm2021.2.2`
* 操作系统版本（如 Mac OS 10.15.6）: `win11`

**Comment by nobodxbodon** [comment]
从源码本地运行，在PhpStorm下问题可复现：
<img width="235" alt="Screen Shot 2022-08-12 at 11 06 43 AM" src="https://user-images.githubusercontent.com/392497/184418142-289e4377-b55d-4919-8024-e6b9c0af774f.png">

Java没问题：
<img width="393" alt="Screen Shot 2022-08-12 at 11 03 29 AM" src="https://user-images.githubusercontent.com/392497/184418123-e6c5a15b-d1b4-4d12-b772-f43bbccbc3ac.png">

好像改回上一版本的 ChinesePrefixMatcher.kt 也有相同问题。也许与 #37 有相同原因？

**Comment by tuchg** [comment]
> 好像改回上一版本的 ChinesePrefixMatcher.kt 也有相同问题。也许与 #37 有相同原因？

#37 我没能复现
