### ISSUE TITLE
【请教】想请教下大佬Intellij怎么支持中英混合的排版

### ISSUE THREAD

**Issue by zxt385189207** [tuchg/ChinesePinyin-CodeCompletionHelper#67]
像下面这样的代码，可以做到自动等号对齐吗？ 谢谢大佬。
```
    中   = 0,
    中文  = 0,
    中文字 = 0,
    A   = 0,
    AA  = 0,
    AAA = 0
```

**Comment by tuchg** [comment]
<img width="723" alt="image" src="https://user-images.githubusercontent.com/24775733/193486556-5ab324e9-cc5d-4013-aa59-6508bd0ad654.png">

可以直接配置code style实现
