### ISSUE TITLE
【Bug】候选词无效

### ISSUE THREAD

**Issue by sxin0** [tuchg/ChinesePinyin-CodeCompletionHelper#68]
## 请事先检查下列事项

- [ x] 已了解或使用过本项目
- [ x]  issue/feature 尚未有前人提出

## 编程语言
> golang

## 预期表现
> 候选词正常展示

## 重现错误场景

> 提供代码片段或截图
![image](https://user-images.githubusercontent.com/29392026/199210564-c06630d6-b507-4c00-a434-58f3ef334ada.png)

## 使用环境

* 插件版本:0.1.11
* IDE版本（如 IDEA 2020.2）:GoLand 2021.2.2
* 操作系统版本（如 Mac OS 10.15.6）:win11

**Comment by tuchg** [comment]
请使用2022.2以上版本，以下版本部分语言被ide内部拦截，需要使用ASCII码作为首位才能触发

**Comment by qq294716498** [comment]
2023.1.2 Rider 编写c#代码只有0.1.9a有效，最新的1.0.0依然无效，不出中文变量名
