### ISSUE TITLE
有在 AS 下用过的了

### ISSUE THREAD

**Issue by nobodxbodon** [tuchg/ChinesePinyin-CodeCompletionHelper#7]
特来告知一声：
![AS 中文补全插件](https://user-images.githubusercontent.com/392497/93734812-a415ab00-fb8f-11ea-892f-d9c4aeb97628.png)

**Comment by tuchg** [comment]
呃呃,AS当然可以,最近鸿蒙那个如果没改的太过分,应该也可以
