### ISSUE TITLE
【建议】到底应该如何导入自然码双拼呢? 

### ISSUE THREAD

**Issue by yangxinyi-bigdata** [tuchg/ChinesePinyin-CodeCompletionHelper#78]
在案例中我看到了小鹤双拼, 但我用的是自然码双拼方案
在 https://github.com/rime/rime-double-pinyin 
这个页面有一个自然码的schema
[double_pinyin.schema.yaml](https://github.com/rime/rime-double-pinyin/blob/master/double_pinyin.schema.yaml)
但是这个似乎是依赖于明月拼音, 并没有一个直接的dict文件, 所以我要如何在插件中导入这个字典呢? 
我并不能直接导入schema使用啊!
希望能出一个说明, 如何导入自然码双拼方案, 万分感谢!
![CleanShot 2024-02-23 at 11 49 33@2x](https://github.com/tuchg/ChinesePinyin-CodeCompletionHelper/assets/37933389/7c0ea929-5fc6-4fe4-863a-e2c933ea68a0)

**Comment by nobodxbodon** [comment]
用明月拼音的dict可否？

**Comment by yangxinyi-bigdata** [comment]
> 用明月拼音的dict可否？

明月拼音是全拼的, 我想要的是双拼自然码, 不过我已经自己找到了一个词库, 自己处理了一下现在可以正常使用了!

**Comment by AutumnPizazz** [comment]
> 明月拼音是全拼的, 我想要的是双拼自然码, 不过我已经自己找到了一个词库, 自己处理了一下现在可以正常使用了!

大佬，我也用的自然码双拼，我需要你的词库QAQ

**Comment by yangxinyi-bigdata** [comment]
> > 明月拼音是全拼的, 我想要的是双拼自然码, 不过我已经自己找到了一个词库, 自己处理了一下现在可以正常使用了!
> 
> 大佬，我也用的自然码双拼，我需要你的词库QAQ
[Uploading 自然码单字版V3.dict.txt…]()

**Comment by AutumnPizazz** [comment]
@yangxinyi-bigdata 你的链接原地TP了，是我理解错了嘛

**Comment by yangxinyi-bigdata** [comment]
> @yangxinyi-bigdata 你的链接原地TP了，是我理解错了嘛
可以通过这个链接下载哈
https://github.com/yangxinyi-bigdata/ChinesePinyin-CodeCompletionHelper/blob/511323b220e70006be7c73acdb031374ff475627/dict/%E8%87%AA%E7%84%B6%E7%A0%81%E5%8D%95%E5%AD%97%E7%89%88V3.dict.yaml
