### ISSUE TITLE
IDEA里面, Ctrl+N 搜索类, 找不出来

### ISSUE THREAD

**Issue by tldzyx** [tuchg/ChinesePinyin-CodeCompletionHelper#8]
![image](https://user-images.githubusercontent.com/5987706/94507362-2a8e5480-0242-11eb-83a5-de79ffb2e15c.png)

**Comment by tuchg** [comment]
平台相关API尚处试验阶段,且使用频率不高,暂且搁置

**Comment by tldzyx** [comment]
> 平台相关API尚处试验阶段,且使用频率不高,暂且搁置

IDEA里面这个几乎每天都用, 根据部分类名找类的时候, 有别的方法替代吗 ?

**Comment by tuchg** [comment]
> > 平台相关API尚处试验阶段,且使用频率不高,暂且搁置
> 
> IDEA里面这个几乎每天都用, 根据部分类名找类的时候, 有别的方法替代吗 ?

😂暂时先用手搓?这块 API是 2020.2 刚开放的接口,而且开放性不高,暂时先不考虑适配了,等几个版本再看看

**Comment by tuchg** [comment]
[官方 IDEA-251113 已提供支持](https://github.com/JetBrains/intellij-community/commit/71a587c4b23667bb09d1f1dc830647b133953a9e)
