### ISSUE TITLE
在IntelliJ IDEA 2024.2.4 中遇到异常

### ISSUE THREAD

**Issue by FireworkRocket** [tuchg/ChinesePinyin-CodeCompletionHelper#82]
## 请事先检查下列事项

- [x] 已了解或使用过本项目
- [x]  issue/feature 尚未有前人提出

## 编程语言
Java

## 预期表现
-

## 当前表现
发生异常
[2024-11-21.txt](https://github.com/user-attachments/files/17843213/2024-11-21.txt)

## 可能的解决方案
-

## 重现错误场景
IntelliJ IDEA 2024.2.4 (Ultimate Edition)
Build #IU-242.23726.103, built on October 23, 2024
Runtime version: 21.0.4+13-b509.26 amd64 (JCEF 122.1.9)
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o.
Toolkit: sun.awt.windows.WToolkit
Windows 11.0
GC: G1 Young Generation, G1 Concurrent GC, G1 Old Generation
Memory: 4096M
Cores: 8
Registry:
  ide.balloon.shadow.size=0
  ide.intellij.laf.enable.animation=true
  ide.experimental.ui=true
  i18n.locale=
Non-Bundled Plugins:
  PythonCore (242.23726.103)
  org.jraf.intellijplugin.nyantray (1.3.5)
  Statistic (4.3.2)
  CheckStyle-IDEA (5.98.0)
  Pythonid (242.23726.103)
  com.github.tuchg.nonasciicodecompletionhelper (1.0.1)
  com.github.copilot (1.5.29.7524)
Kotlin: 242.23726.103-IJ

> 提供代码片段或截图
![image](https://github.com/user-attachments/assets/17e53c63-60a7-4d65-8baa-6af960ee2a4b)

## 使用环境
i3-12100
![image](https://github.com/user-attachments/assets/b1650d2b-ef0b-457d-8475-a8cb14beba50)

* 插件版本:1.0.1
* IDE版本（如 IDEA 2020.2）:IntelliJ IDEA 2024.2.4 (Ultimate Edition)
* 操作系统版本（如 Mac OS 10.15.6）:Windows11 23H2

**Comment by nobodxbodon** [comment]
你好，请问有方法重现此问题吗？
另外，可否将 stacktrace.txt 完整内容贴一下？ChineseCompletionContributor 的行号看不到。

**Comment by FireworkRocket** [comment]
> 你好，请问有方法重现此问题吗？ 另外，可否将 stacktrace.txt 完整内容贴一下？ChineseCompletionContributor 的行号看不到。


很奇怪，只有那一天内出现了这个问题，这几天都没有遇到了
